Repository shuwax/crm, pull requests merged in 2018-08, with the labels that each got.

#921 Development
  app/ClientRouteCampaigns.php
  app/Http/Controllers/CrmRouteController.php
  resources/views/crmRoute/showClientRoutes.blade.php
Labels: bug

#922 Change: aheadPlanning.blade.php - highlited actual day
  app/Http/Controllers/CrmRouteController.php
  resources/views/crmRoute/aheadPlanning.blade.php
Labels: enhancement

#925 Adding simulation object template
  app/Http/Controllers/CrmRouteController.php
  resources/views/crmRoute/aheadPlanning.blade.php
Labels: enhancement

#971 Simulation changes
  resources/views/crmRoute/aheadPlanning.blade.php
Labels: bug, enhancement

#978 Change
  app/Http/Controllers/CoachingController.php
  resources/views/coaching/progress_table_for_coach.blade.php
  resources/views/crmRoute/showClientRoutes.blade.php
Labels: bug

#980 Fix: aheadPlanning.blade.php - simulated result in simulation is roun…
  app/Http/Controllers/CrmRouteController.php
  resources/views/crmRoute/aheadPlanning.blade.php
Labels: bug
